services:
  gocker:
    build:
      dockerfile: build.Dockerfile
    ports: 
      - "3000:3000"
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  backend:
