/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as ContainerIndexImport } from "./routes/container/index";
import { Route as ContainerContainerIdImport } from "./routes/container/$containerId";

// Create Virtual Routes

const AboutLazyImport = createFileRoute("/about")();
const IndexLazyImport = createFileRoute("/")();

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/about.lazy").then((d) => d.Route));

const IndexLazyRoute = IndexLazyImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

const ContainerIndexRoute = ContainerIndexImport.update({
  id: "/container/",
  path: "/container/",
  getParentRoute: () => rootRoute,
} as any);

const ContainerContainerIdRoute = ContainerContainerIdImport.update({
  id: "/container/$containerId",
  path: "/container/$containerId",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/container/$containerId": {
      id: "/container/$containerId";
      path: "/container/$containerId";
      fullPath: "/container/$containerId";
      preLoaderRoute: typeof ContainerContainerIdImport;
      parentRoute: typeof rootRoute;
    };
    "/container/": {
      id: "/container/";
      path: "/container";
      fullPath: "/container";
      preLoaderRoute: typeof ContainerIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexLazyRoute;
  "/about": typeof AboutLazyRoute;
  "/container/$containerId": typeof ContainerContainerIdRoute;
  "/container": typeof ContainerIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexLazyRoute;
  "/about": typeof AboutLazyRoute;
  "/container/$containerId": typeof ContainerContainerIdRoute;
  "/container": typeof ContainerIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexLazyRoute;
  "/about": typeof AboutLazyRoute;
  "/container/$containerId": typeof ContainerContainerIdRoute;
  "/container/": typeof ContainerIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/about" | "/container/$containerId" | "/container";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/about" | "/container/$containerId" | "/container";
  id: "__root__" | "/" | "/about" | "/container/$containerId" | "/container/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  AboutLazyRoute: typeof AboutLazyRoute;
  ContainerContainerIdRoute: typeof ContainerContainerIdRoute;
  ContainerIndexRoute: typeof ContainerIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  ContainerContainerIdRoute: ContainerContainerIdRoute,
  ContainerIndexRoute: ContainerIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/container/$containerId",
        "/container/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/container/$containerId": {
      "filePath": "container/$containerId.tsx"
    },
    "/container/": {
      "filePath": "container/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
